### ISSUE TITLE
Anonymous questioners - true name shown after updating their post

### ISSUE THREAD

**Issue by luethen** [learnweb/moodle-mod_moodleoverflow#104]
Dear learnweb Team,

Thank you very much for this nice plugin, our students are using it a lot!

We use the Moodleoverflow forum with the setting "Anonymous: Only questioners". Today I edited the caption of one of the anonymous questions. After saving, Moodle showed me a message "Successfully updated \<Student Name\>'s post" with the full student name. I thought I'd let you know, it's harmless but probably not intended.

Thanks and best wishes,
Nora

**Comment by justusdieckmann** [comment]
Hi @luethen,
thank you very much for the bug report! It is now fixed on the master branch.
Cheers
Justus
