### ISSUE TITLE
Daily digest of e-mail notifications planned?

### ISSUE THREAD

**Issue by gergelyrakoczi** [learnweb/moodle-mod_moodleoverflow#112]
We at TU Wien use this great plugin and are wondering if the feature of digest e-mails (summary of e-mail notifications of one day) is planned as a new feature. Currently teachers and students receive single-mails. Specially, in large courses this can be quite overwhelming. So if you plan to implement a digest function (as moodle standard forum does) we would be highly delighted.
In case I have missed this functionality in the current version, please let me know.
And keep up the great work, thank you - this plugin is great!
Best regards from Vienna,
Gergely Rakoczi

**Comment by NinaHerrmann** [comment]
Hey @gergelyrakoczi,
happy you like the plugin! :partying_face: 
Just wondering - would you rather think a specific/distinct setting would be required or use the decision from the `mod/forum` setting? 
Cheers!

**Comment by gergelyrakoczi** [comment]
Dear @NinaHerrmann,
thank you for your fast response and indeed this is a good question. We at TU Wien see the moodleoverflow forum as one part of Moodle's forum portfolio. So following this the user's digest preference should be used for all forums in Moodle across all courses - so all news forums, standardforums, moodleoverflows etc. This means the setting "Email digest type" under profile / preferences / forum preferences should be taken into account. I guess this is the same as the decision from mod/forum what you have written.  
Hope this helps. :)
Cheers,
Gergely

**Comment by NinaHerrmann** [comment]
Thanks @gergelyrakoczi I think this makes sense, and I consider this a rather easy issue :+1:

**Comment by gergelyrakoczi** [comment]
Wonderful this sounds great! Thank you @NinaHerrmann

**Comment by NinaHerrmann** [comment]
Is implemented and merged

**Comment by gergelyrakoczi** [comment]
Fantastic @NinaHerrmann ! Thank you very much. We will check out the new version, I'm thrilled to see the new feature! Thank you! And in case of feedback, I will come back to you. Cheers, G.
