### ISSUE TITLE
Bug report: attatched images do not display after upgrade

### ISSUE THREAD

**Issue by pejhab** [learnweb/moodle-mod_moodleoverflow#144]
Screenshot 1

![image](https://github.com/learnweb/moodle-mod_moodleoverflow/assets/4097425/0b44a000-652f-4266-8d11-613520584c5f)

Screenshot 2

![image](https://github.com/learnweb/moodle-mod_moodleoverflow/assets/4097425/56346ead-1ed1-4816-8f91-a6f345e9a36b)

Screenshot 3 (page source)

![image](https://github.com/learnweb/moodle-mod_moodleoverflow/assets/4097425/67c9938d-8cc7-453d-a0c3-2d7a7df46521)

**Comment by pejhab** [comment]
Students report the same problem. Some posts in which users are expected to comment on pictures are basically unusable because of this.

**Comment by NinaHerrmann** [comment]
Thanks for supporting, we are on it in #145

**Comment by NinaHerrmann** [comment]
#146 Fixes it release is comming!

**Comment by NinaHerrmann** [comment]
Release is available in the Plugin Directory.
