### ISSUE TITLE
Exception opening attached files

### ISSUE THREAD

**Issue by Marx1st** [learnweb/moodle-mod_moodleoverflow#152]
Hi!

We've recently upgraded Moodleoverflow to v4.2-r1 2023052200 on our Moodle 3.11.14+ site.

After that files attached to posts can not be opended anymore (neither existing or newly added files).

The error:

`Exception - Call to a member function is_external_file() on bool

[More information about this error](https://docs.moodle.org/311/en/error/moodle/generalexceptionmessage)
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 2719 of /lib/filelib.php: Error thrown
    line 465 of /mod/moodleoverflow/lib.php: call to send_stored_file()
    line 5156 of /lib/filelib.php: call to moodleoverflow_pluginfile()
    line 44 of /pluginfile.php: call to file_pluginfile()`

The problem did not exist with Moodleoverflow v4.1-r1 2022120600.

**Comment by NinaHerrmann** [comment]
Already mentioned in #144 and work in progress in #146

**Comment by NinaHerrmann** [comment]
There is a release fixing the issue (4.2-r2) :)
