### ISSUE TITLE
Bug report: broken main page format (double page numbering)

### ISSUE THREAD

**Issue by pejhab** [learnweb/moodle-mod_moodleoverflow#154]
Moodle 4.1+ (Build: 20221209) and Overflow v4.2-r2 2023070300:

<img width="613" alt="image" src="https://github.com/learnweb/moodle-mod_moodleoverflow/assets/4097425/c3d2073b-8f96-460d-86a4-94fcb74d207b">

Pretty sure this was OK before the latest update. 

This is just at the top. The bottom one is OK.

**Comment by NinaHerrmann** [comment]
#155 might solve this - test need to run

**Comment by pejhab** [comment]
Thanks!
