### ISSUE TITLE
Bug - Teacher receives wrong notifications 

### ISSUE THREAD

**Issue by mdorferf** [learnweb/moodle-mod_moodleoverflow#167]
We have received feedback about a strange behavior regarding E-mail notifications: 
One of our teachers uses Moodleoverflow and E-mail notifications about new posts regularly in his course, but also received a notification from a Moodleoverflow activity in a course he was never enrolled in. The course triggering the incorrect notification is in a different course category and the teacher has no capabilities in that course. 
We can neither explain nor reproduce this bug. Do you have any hints or tips as to what could have caused this behavior?

**Comment by mdorferf** [comment]
Attached is a screenshot of the settings of the Moodleoverflow activity that caused a false notification. 
![Uploading Settings of Moodleoverflow activity_231117.jpg…]()

**Comment by NinaHerrmann** [comment]
sounds like capabilities might not be set correctly. Which moodleoverfloe version do you use?

**Comment by mdorferf** [comment]
Hi Nina, 
thank you for your quick reply! We are using the version 2023052200. Do you have any suggestions as to which capabilities we should take a closer look at?

**Comment by NinaHerrmann** [comment]
Hey @mdorferf - this is the version having the userstats feature right? I fear you have to update to 2023052201 and disable the feature.
We did not have time to look into it, but it seems to break something.

**Comment by ziegenberg** [comment]
This only seems to happen to the digest mails.

**Comment by NinaHerrmann** [comment]
@TamaroWalter Could you check that?

**Comment by TamaroWalter** [comment]
Of course!

**Comment by TamaroWalter** [comment]
@mdorferf, @ziegenberg  we checked your problem in our systems but everything seems working fine with the digest mails.
Do you know how often the problem occured?
My fastest advice would be to update moodleoverflow to a newer version.

**Comment by mdorferf** [comment]
@TamaroWalter Thank you for checking! We updated our moodloverflow activity to a newer version already but it still occurs in our system. We have three users who report to us regularly in tickets. The number of unreported cases is probably higher.

**Comment by TamaroWalter** [comment]
@mdorferf alright, then there must be a problem, I will try to find the error! You are using the new release v4.2-r4 right? What kind of database are you using?

**Comment by NinaHerrmann** [comment]
They are using 2023052200 which is v4.2-r1.

**Comment by ziegenberg** [comment]
As we have updated we are now running 2023082500 which is v4.2-r4 and the error still occurs.

**Comment by mdorferf** [comment]
@TamaroWalter Unfortunately, this error has occurred again with another person (role = teacher). May we ask if there is anything new about this issue?

**Comment by NinaHerrmann** [comment]
We are working on it in #176 
If this is possible for you, you can include those lines to  [classes/task/send_daily_mail.php](https://github.com/learnweb/moodle-mod_moodleoverflow/pull/176/files#diff-7c3e9a722969d9c17674d677f05d8e28407b0df3d459ca6a5810805dc336f0e4)
```PHP
if (!is_enrolled(\context_course::instance($row->courseid), $user->userid, '', true)) {
    continue;
}
 ```
 (l.60 after assigning `$currentcourse` and before `$currentforum`)
 I am sorry for the really slow bug fix. We are currently very limited in our resources and therefore slower than usual.

**Comment by mdorferf** [comment]
Many thanks for the quick reply and the suggestion! I've already passed it on to our developers and we'll take a closer look at it.
