### ISSUE TITLE
Sorting responses

### ISSUE THREAD

**Issue by gergelyrakoczi** [learnweb/moodle-mod_moodleoverflow#172]
We at TU Wien have a question concerning your great plugin. When a forum is operated in an anonymous mode (Questioners and answerers (irreversible!)) the sorting of the responses is unclear for the teachers. Often newest replies appear in-between of older messages (see screenshot below). In the activity settings, we could not obtain any parameters to configure the sorting order. Did we miss a setting on the module or admin level or somewhere else? Based on what parameter(s) is the sorting done?

Thank you for your help in advance and keep up the great work on this awesome plugin.

![Moodleoverflow Sortierung unklar](https://github.com/learnweb/moodle-mod_moodleoverflow/assets/106730052/3d1f26d4-9aa4-4f17-897a-71df94447f4f)

**Comment by NinaHerrmann** [comment]
Hey, thank you for reporting the weird behavior! 
I tried to reproduce it, but our instance's answers are chronologically ordered. 
Does this happen rarely or always - and which version are you using? Thank you for your help!

**Comment by gergelyrakoczi** [comment]
Hi Nina, thank you for your reply. It happens quite often. We are on code version v4.2-r4 2023082500.
Currently, we believe that the sorting order of the sub-answers might be influenced somehow by the role and the user itself. See here another example with 5 responses an the entire thread of questions and answers. Hope this helps.

![17-01-2024_08-03-55](https://github.com/learnweb/moodle-mod_moodleoverflow/assets/106730052/83aa606c-c80c-4b80-87e5-118002ba0a77)

**Comment by TamaroWalter** [comment]
Hi, I checked this bug and I can reproduce it. Apparently there is a problem with our sorting system. I'm on this issue!
