### ISSUE TITLE
Check which / how many students are subscribed to a moodleoverflow forum

### ISSUE THREAD

**Issue by tpapastylianou** [learnweb/moodle-mod_moodleoverflow#174]
Hello.

This is effectively the same issue as #107 which still remains unsolved. Not sure why it was closed as fixed by #108, since this does not address any of the points.

In any case, as per #107, while I am still unable to manage or view subscriptions _**(of my students, not my own),**_ I have partially solved my problem this year by making all subscriptions 'optional' and asked my students to subscribe 'manually', so as to avoid other participants (e.g. admins / guest lecturers) from being bombarded with spam this year.

However, moodleoverflow does not provide a 'manage subscriptions' facility like other forums, so I am unable to check how many of my students have subscribed to the forum or not. At least not the version used by my university.

As per #107, I was wondering if there is a secret/hacky method of doing so? E.g. some sort of .php address that I can add parameters to to get that kind of check / list?

Thanks

Moodle version: 4.2.2

**Comment by tpapastylianou** [comment]
I have found a workaround, along the same lines as [this stackoverflow post](https://stackoverflow.com/a/11662806)

Steps:

1.  Make a backup of the moodleoverflow forum. Make sure to include enrolled users.
2. Save the backup file, and change the extension from .mbz to .tar.gz
3. Extract the .tar.gz file and check the users.xml file. This contains xml entries including users / usernames/ids that you can count.

Leaving this open in case the team might want to work a bit more formally on this, or for the benefit of anyone else having the same issue. Otherwise this workaround solves my issue, even if a bit hacky, in which case feel free to close.

**Comment by NinaHerrmann** [comment]
Hey @tpapastylianou ,
I tested the following steps:
1) prevent the `moodleoverflow:allowforcesubscribe` permission in the admin menu Users-Permissions in your case the non-editing teacher role
2) assign the role to the user in a course
3) write a post in a moodleoverflow forum with forced subscription
4) the user does not get a mail for the post

Please check if you could test if those steps work for you.

**Comment by tpapastylianou** [comment]
Hi @NinaHerrmann, thanks for this. Presumably this refers to #107 rather than this, right?
However, the link to #108 now also makes sense, thank you for the explanation of how this should work.
I don't have an active course to test this on at the moment, but will try this in the next academic year.
Many thanks!
T.

**Comment by NinaHerrmann** [comment]
Hey @tpapastylianou, alright then I will close it for now. Please reopen it in case the steps can not solve the issue.
