### ISSUE TITLE
Bug - Settings are reset after import

### ISSUE THREAD

**Issue by mdorferf** [learnweb/moodle-mod_moodleoverflow#177]
We have received the feedback that the Moodleoverflow settings are reset to default after the import from another Moodle course. 

As a teacher, I would expect the settings to be unchanged after the import. 

**Reproduce the bug:**

- Create a new course with a Moodleoverflow activity. 
- Change the default settings to "Anonymous > Questioners and answerers (Irreversible!)" and "Maximum grade > 10". Save the settings. 
- Create a second new course. 
- Import the Moodleoverflow activity of the first course in the second course. 
- Result: The Moodleoverflow activity settings in the second course are set to default " "Anonymous > No" and the "Maximum grade > -".

Moodle version: 4.3
Plugin version: 2023082500

![Moodloverflow_Import_#1 course](https://github.com/learnweb/moodle-mod_moodleoverflow/assets/103104029/cf74f555-daf5-4feb-b806-9595fe8a95ef)
![Moodloverflow_Import_#2 course](https://github.com/learnweb/moodle-mod_moodleoverflow/assets/103104029/5d7355e0-5fcc-4ae8-8799-7a2cd56bd6bf)

Thank you for your help!

**Comment by TamaroWalter** [comment]
Hi @mdorferf, i checked your bug and there where some information missing in our backup-functions that are used to import a moodleoverflow acitivty to another course. The problem should be solved now.

**Comment by mdorferf** [comment]
Hi @TamaroWalter, 
Wow, that was quick. Thank you very much for the explanation and the solution :-)

**Comment by NinaHerrmann** [comment]
Noteworthy the issue is solved in #179 but I still need to review it :see_no_evil:
