### ISSUE TITLE
Time error?

### ISSUE THREAD

**Issue by dinism** [learnweb/moodle-mod_moodleoverflow#18]
Is this a mistake?
In moodleoverflow.php, [line 96](https://github.com/learnweb/moodle-mod_moodleoverflow/blob/master/lang/en/moodleoverflow.php#L96)
One hour is 3600 s
Half hour is 1800 s
Thanks for plugin

**Comment by Dagefoerde** [comment]
Yes indeed, sorry for that! 3600 is correct (https://github.com/learnweb/moodle-mod_moodleoverflow/blob/913c38c9b9e380fd726a572132ea46248b1a5b73/settings.php#L49) so the text should say "1 hour".
