### ISSUE TITLE
Problems following upgrade

### ISSUE THREAD

**Issue by pejhab** [learnweb/moodle-mod_moodleoverflow#190]
Hello,

I have recently upgraded to Moodleoverflow v4.4-r1 and now video filters have stopped working (Generico and generic Moodle video embed). I am further looking into this. 

Have you had similar reports?

Regards,

P.H.

**Comment by pejhab** [comment]
To clarify, the Generico filter works fine if I use it to embed a video in a post on a Moodle standard forum, but it fails on Moodle overflow.

STARNDARD FORUM:

![image](https://github.com/user-attachments/assets/c00ee93b-666a-49b0-8188-65dda6c4c6d4)

OVERFLOW:

![image](https://github.com/user-attachments/assets/130faa7d-8ce1-4c39-ba63-89275dec4042)

My Moodle version: 4.1+ (Build: 20221209)

**Comment by pejhab** [comment]
I have also noticed that glossary linking no longer works on Moodleoverflow.

**Comment by NinaHerrmann** [comment]
@TamaroWalter Could you please test that?

**Comment by pejhab** [comment]
Could you please confirm this as a bug? All our videos on all our Moodleoverflow forums have stopped working.

**Comment by NinaHerrmann** [comment]
Please remember that this is not our fulltime job. @TamaroWalter will probably look into that tomorrow.

**Comment by TamaroWalter** [comment]
Hello @pejhab,
thank you for reporting an issue. I tried to reproduce your problem on my system and indeed, there is a bug while formating embedded videos in Moodleoverflow. I am on this issue!

**Comment by TamaroWalter** [comment]
Hello @pejhab,
I committed a fix in #191 and embedded videos are now working on my moodle systems (M4.4 and M4.1). If you want, you can add the changes to your system and test if it works too. If you do, please report it so I can either continue searching for the bug or add the changes to the productive system.
Regards
Tamaro

**Comment by pejhab** [comment]
Hello,
I replaced the two files with the modified versions and Generico video embedding, standard video embedding, and glossary auto-linking all seem to be working properly again. 
Thanks for your time and effort!

**Comment by Laur0r** [comment]
Hello, these problems should be fixed with v4.4-r3.
