### ISSUE TITLE
In-line images are not shown

### ISSUE THREAD

**Issue by roessling** [learnweb/moodle-mod_moodleoverflow#194]
When I post an article in a moodleoverflow and use the „image“ icon to add the image, it is not shown (only a placeholder with a „?“).
If the image is posted via attachment => add file, it is shown.
Environment: Moodle 4.4.1+ (20240802)
Moodle-Overflow: version 2024072500

**Comment by Laur0r** [comment]
This is fixed with the changes in #193 . However, due to current errors in the moodle-plugin-ci , the new release is delayed.

**Comment by roessling** [comment]
Thank you for the information. Looking forward to seeing it fixed whenever the plugin allows it ;-)

**Comment by Laur0r** [comment]
Should be fixed with v4.4-r3
