### ISSUE TITLE
Single Activity Format - error

### ISSUE THREAD

**Issue by jdmagnore** [learnweb/moodle-mod_moodleoverflow#197]
Moodle version: 4.1
Plugin version: 2024082700

Reproduce the error:

1) Create new couser
2) Select "Course format" --> "Single Activity Format"
3) Select "Moodleoverflow"
4) Save and display
5) Put a name for Moodleoverflow activity
6) Go to participants --> ERROR: Exception - Argument 1 passed to is_enrolled() must be an instance of context, null given, called in [dirroot]/mod/moodleoverflow/lib.php on line 478 (If you try to go to any other Course submenu you see this Exception)

Could you try to fix it? Thanks in advance 😊👍

**Comment by TamaroWalter** [comment]
Hi,

thank you for your report. I tested it on my system and experience the same bug. I'm on it!

**Comment by TamaroWalter** [comment]
Hi, i pushed a little commit that seems to solve the problem. Feel free to try it out if you like!

**Comment by xmontana** [comment]
> Hi, I pushed a little commit that seems to solve the problem. Feel free to try it out if you like!

Thank you Tamaro, I confirm that it works 😁

**Comment by jdmagnore** [comment]
Thank you!!!! 😊👍
