### ISSUE TITLE
Bug: Missing string

### ISSUE THREAD

**Issue by Kathrin84** [learnweb/moodle-mod_moodleoverflow#25]
Hi,

we've encountered that a string in the notification preferences is missing for your plugin.
It is shown as [[messageprovider:posts]] and can be found on page /message/notificationpreferences.php.

Cheers, Kathrin

**Comment by Dagefoerde** [comment]
Hi Kathrin, thanks for noticing. This will be fixed with our release for Moodle 3.5, coming out later today.
