### ISSUE TITLE
Support anonymous questions / user disguises

### ISSUE THREAD

**Issue by abias** [learnweb/moodle-mod_moodleoverflow#28]
Based on our teachers' feedback, I would like to propose to add support anonymous questions / user disguises to Moodleoverflow.

The user stories are:
1. As a student, I would like to be able to ask questions anonymously to prevent making a fool of myself. I am afraid that others will think I am dumb if I ask dumb questions. I am also afraid that my teacher might give me a bad mark if I ask dumb questions.
2. As a teacher, I would like to give my students the possibility to ask questions anonymously because otherwise they wouldn't ask the questions at all.

I am aware that these arguments are arguable and that there are arguments out there which show that anonymous posts are useful as well as arguments which show that anonymous posts are harmful for the discussion outcome. However, this issue is just about the technical view, not the pedagogical view.

To implement anonymous questions, you could either:
* Implement a module-specific solution in Moodleoverflow
* Add support for user disguises from Moodle core (https://tracker.moodle.org/browse/MDL-1071) which unfortunately hasn't landed yet.

When implementing anonymous questions, you especially have to decide:
* If only the initial post in a topic should be anonymous (so that nobody knows who posted the dumb question)
* If a student posts should be anonymous (so that all students can discuss freely)
* If also the teacher / staff should post anonymously
* How anonymous posts will work with / influence the reputation count and the solution flags in Moodle overflow

**Comment by Dagefoerde** [comment]
Hi @abias, thanks for you detailed report.
As you stated, an implementation of MDL-1071 would be the preferred way to go, so implementing a plugin-specific solution is not on our radar right now. 

Regardless, in the meantime we welcome code contributions that achieve support for anonymous questions. Any help is much appreciated and will be reviewed by us.

**Comment by NinaHerrmann** [comment]
Close this as it was implemented in #81 (and not closed).
