### ISSUE TITLE
Embedding youtube videos breaks layout

### ISSUE THREAD

**Issue by Marx1st** [learnweb/moodle-mod_moodleoverflow#31]
Hi,

when answering a post (not when opening a new topic) and adding a youtube video link (haven't tested with different video providers), the video gets embedded into the text.
There is no error message when saving the post, but the layout is broken and there are no links (perma link, edit link, etc.) beneath the post (see screenshot).

We are using Moodle 3.5.2 with the Moodle Boost Campus theme (v3.5-r2).

Regards
Tobias

![bildschirmfoto 2018-11-15 um 14 33 43](https://user-images.githubusercontent.com/7048232/48557643-97ff9900-e8e7-11e8-951c-1c0df3e4ce0c.png)

**Comment by Dagefoerde** [comment]
Hi Tobias,
Thanks for your report. What does the HTML code around that area look like?
Also, if you can propose a code solution please feel free to file a pull request. We'd be grateful for any help.
Cheers,
Jan

**Comment by Marx1st** [comment]
Here's the HTML:

`<div class="moodleoverflowpost clearfix read" role="region" aria-label="Bub von Tobias Marx">

    <table>
        <tbody>
            <tr>
                <td class="votecell">
                    <div class="votes">
                        
                                <img class="icon " alt="Keine positive Bewertung" title="Keine positive Bewertung" src="https://moodle.uni-wuppertal.de/theme/image.php/boost_campus/moodleoverflow/1539947938/vote/upvote" />
                        
                        <p>0</p>
                        
                                <img class="icon " alt="Keine negativen Bewertungen" title="Keine negativen Bewertungen" src="https://moodle.uni-wuppertal.de/theme/image.php/boost_campus/moodleoverflow/1539947938/vote/downvote" />
                    </div>
                </td>
                <td class="answercell">
                    <div class="post-text">
                        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus <div class="mediaplugin mediaplugin_videojs"><div style="max-width:400px;"><video data-setup-lazy="{&quot;techOrder&quot;: [&quot;youtube&quot;], &quot;sources&quot;: [{&quot;type&quot;: &quot;video/youtube&quot;, &quot;src&quot;:&quot;https://www.youtube.com/watch?v=SsR_4iqyPgM&quot;}], &quot;language&quot;: &quot;de&quot;, &quot;fluid&quot;: true}" id="id_videojs_5bee878107ddd_2" class="video-js" preload="auto" controls="true" title="est Lorem ipsum dolor sit amet."><a class="mediafallbacklink" href="https://www.youtube.com/watch?v=SsR_4iqyPgM">est Lorem ipsum dolor sit amet.</a></video></div></div><br /></p>
                    </div>
                    <div class="attachments">
                    </div>
                    <table class="post-info">
                        <tbody>
                            <tr>
                                <td class="leftbox">
                                    <div class="user-info">
                                        <div class="user-avatar">
                                            <a href="https://moodle.uni-wuppertal.de/user/view.php?id=3&amp;course=692"><img src="https://secure.gravatar.com/avatar/1555f955da36229e2afcc101c2faa7f0?s=35&amp;d=mm" alt="Nutzerbild Tobias Marx" title="Nutzerbild Tobias Marx" class="userpicture defaultuserpic" width="35" height="35" /></a>
                                        </div>
                                        <div class="user-details">
                                            <a href="https://moodle.uni-wuppertal.de/user/view.php?id=3&amp;course=692">Tobias Marx</a> (<img class="icon " alt="Reputation" title="Reputation" src="https://moodle.uni-wuppertal.de/theme/image.php/boost_campus/moodleoverflow/1539947938/star" /><span>0</span>)
                                            <div class="-flair">
                                                <div class="user-action-time">
                                                    Donnerstag, 15. November 2018, 14:33
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td class="rightbox">
                                    <div class="status">

                                    </div>
                                    <div class="post-menu">
                                        <a href="https://moodle.uni-wuppertal.de/mod/moodleoverflow/discussion.php?d=33#p87">Permalink</a> | <a href="https://moodle.uni-wuppertal.de/mod/moodleoverflow/discussion.php?d=33&amp;sesskey=1fNw33TERA&amp;r=4&amp;rp=87">Als hilfreich markieren</a> | <a href="https://moodle.uni-wuppertal.de/mod/moodleoverflow/discussion.php?d=33&amp;sesskey=1fNw33TERA&amp;r=3&amp;rp=87">Als gelöst markieren</a> | <a href="https://moodle.uni-wuppertal.de/mod/moodleoverflow/post.php?edit=87">Bearbeiten</a> | <a href="https://moodle.uni-wuppertal.de/mod/moodleoverflow/post.php?delete=87">Löschen</a> | <a href="https://moodle.uni-wuppertal.de/mod/moodleoverflow/post.php?reply=87#mformmoodleoverflow">Antworten</a>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>

</div></div>
</div>`
