### ISSUE TITLE
Email notifications don't work with plain text setting

### ISSUE THREAD

**Issue by Marx1st** [learnweb/moodle-mod_moodleoverflow#35]
If a user has set his/her email notifications setting to "Plain text format" instead of "HTML" (message/notificationpreferences.php), notifications mails from Moodleoverflow will not be converted to plain text (like mails from the standard forums), but will display HTML source in plain text.

![bildschirmfoto 2019-02-07 um 10 47 51](https://user-images.githubusercontent.com/7048232/52403023-078bbb80-2ac6-11e9-8996-ee06e5f174c6.png)

**Comment by Dagefoerde** [comment]
Hi Tobias,
Thanks for your report. If you can propose a code solution please feel free to file a pull request. We'd be grateful for any help.
Cheers,
Jan
