### ISSUE TITLE
 Improve "Mark as solved" / "Not solved" link

### ISSUE THREAD

**Issue by Kathrin84** [learnweb/moodle-mod_moodleoverflow#36]
Hi guys,

we have encountered that the "Mark as solved" / "Not solved" links might be misunderstanding.

Explanation:
"Mark as solved" is understood as "This post is solved".
But the semantics of the link is in fact "This is the solution for this thread".
That's why we would propose to rename this link to "Mark as solution" / "Remove solution mark".

Additionally, we have seen that the page is reloaded when you click the "Mark as solved" link and is jumping to the post anchor. This might be confusing. Please think about changing the behaviour to just reload the page without jumping to the post. As a result, the user will see the whole thread on the reloaded page.

Best, Kathrin

**Comment by Dagefoerde** [comment]
Hi Kathrin,
Thanks for your report. If you can propose a code solution please feel free to file a pull request. We'd be grateful for any help.
Cheers,
Jan

**Comment by Dagefoerde** [comment]
Hi Kathrin, I consider this issue closed as per Justus's improvements (#41) that I will merge shortly. If you encounter any problems later, please feel free to open a new pull request!

**Comment by Kathrin84** [comment]
Hi Jan,
happy to hear this. Thanks to Justus for providing the fix.
Best, Kathrin
