### ISSUE TITLE
Upvote and downvote links should not jump to anchor

### ISSUE THREAD

**Issue by Kathrin84** [learnweb/moodle-mod_moodleoverflow#37]
Hi guys,

we've encountered that when a user is upvoting or downvoting a post by using the arrows the page will jump to the position (anchor) of that icon.
This was quite unexpected for us. Our expectation would be that the page would update the information without a new page load (as it does) but also keeps the position of the page.
We also saw that you used javascript:void(0) in the links and that feels strange and a bit outdated.

We would be happy if you would take a look at this. :)

Best, Kathrin

**Comment by Dagefoerde** [comment]
Hi Kathrin,
Thanks for your report. If you can propose a code solution please feel free to file a pull request. We'd be grateful for any help.
Cheers,
Jan

**Comment by Kathrin84** [comment]
Hi Jan,
happy to hear this. Thanks to Justus for providing the fix.
Best, Kathrin
