### ISSUE TITLE
Missing and outdated strings in AMOS

### ISSUE THREAD

**Issue by abias** [learnweb/moodle-mod_moodleoverflow#43]
Hey,

I have noticed that there is a bunch of missing and outdated strings in AMOS for the german language pack which are especially related to the latest version v3.7-r1.

I would appreciate if you could submit the german translation as you, as the plugin maintainer, most probably will find the best german wording.

Cheers,
Alex

**Comment by Dagefoerde** [comment]
Thanks for the report. We will!

**Comment by justusdieckmann** [comment]
All german translations that were missing or outdated (related to #36) were added/updated.

**Comment by abias** [comment]
@justusdieckmann , really? 

As far as I see, these strings are still outdated:
* configvotescalesolved
* moodleoverflow:marksolved
* ratingpreference_help
* votescalesolved

Did you forget to change them or is the translation still only waiting for moderation?

Cheers,
Alex

**Comment by justusdieckmann** [comment]
Sorry, the missing translated strings are now submitted. Thanks for the notice :)
