### ISSUE TITLE
Make this particular forum an actual new forum type

### ISSUE THREAD

**Issue by zabellemotte** [learnweb/moodle-mod_moodleoverflow#45]
Hello, 

Your plugin is very interesting but it adds a new activity in the very long list of activities that exist in Moodle. It would be great to make this forum a new forum type that may be integrated in the default forum activity. 

Best regards,

Zabelle

**Comment by Dagefoerde** [comment]
Hi Zabelle,

Thanks for your feedback! Like you, I am not so fond of making the list of activities longer. Selecting an activity type as a teacher is already hard as it is.

Sadly, the Moodle core activity `mod_forum` does not allow plugins to extend the list of forum types. As a consequence, it is not possible to create a plugin that offers a new forum type. Right now, adding a forum type can only be achieved by hacking Moodle core, or by trying to get this forum type officially accepted into core. Neither is practical or realistic, so for now we will have to continue to offer an additional activity type with this plugin.

Best,
Jan

**Comment by zabellemotte** [comment]
Thanks for answer Jan.

If other people want such implementation of new forum types to become possible, they have to vote for this issue in the Moodle bugtracker :
https://tracker.moodle.org/browse/MDL-62675

All the best !

Zabelle

**Comment by Dagefoerde** [comment]
Hi Zabelle, thank you for pointing to that issue! Indeed, interested people should vote for  https://tracker.moodle.org/browse/MDL-62675 or even suggest a patch that would resolve that issue.
