### ISSUE TITLE
v3.9-r1 - Fix message modification on post editing?

### ISSUE THREAD

**Issue by acquaalta** [learnweb/moodle-mod_moodleoverflow#54]
Hi,
Yesterday (June 16th, 2020), you released version v3.9-r1 of the plugin. According to the release notes, it included the following fix:
**Fix message modification on post editing**

I'm using Moodle 3.8, and upgrading the plugin at this point of the system life, is not something that can be done harshly. So I wonder...

What does this fix actually change? What's the reason for it?
I wonder if it's a "must" or I can keep using version v3.8-r1 for now.

Thanks in advance :-)

**Comment by Dagefoerde** [comment]
Hi @acquaalta , this is the change that was made:
https://github.com/learnweb/moodle-mod_moodleoverflow/commit/52510e8b8f3c54d50dd5de65256f1d2f839323ca

It is just a simple typo that affects the message text when a message is edited. Try editing a message for yourself to see whether you can live with the issue until you can perform an update. If you can't (but also can't update), you can consider changing this simple typo in your Moodle's  files manually.

In any case, note that the new plugin version still works with Moodle 3.8. So it would be possible for you to just update the plugin without updating your entire Moodle.
