### ISSUE TITLE
Provide an overview of participants and their reputation

### ISSUE THREAD

**Issue by Dagefoerde** [learnweb/moodle-mod_moodleoverflow#61]
A happy teacher requested to get an overview of the users that have participated in a Moodleoverflow (or a course) in order to see their reputation. I think this could be displayed as a ranking on a separate page. Teachers should be able to select whether this ranking is publicly accessible or whether it should be visible teachers-only.

**Comment by acquaalta** [comment]
+1

**Comment by NinaHerrmann** [comment]
Implemented in #120
