### ISSUE TITLE
An internal error occurs when configuring the "activity completion" of a “Moodleoverflow” activity.

### ISSUE THREAD

**Issue by Sophia-Xiong** [learnweb/moodle-mod_moodleoverflow#64]
I created a new "Moodleoverflow" activity. Filled in its name. Configured the settings under "Activity completion" as below picture. Clicked "save and return to course" button. Then it showed the error message.
<img width="1500" alt="Screen Shot 2020-09-11 at 2 36 46 PM" src="https://user-images.githubusercontent.com/71122085/92892002-f72e8600-f44a-11ea-9394-831d492abb73.png">
<img width="1537" alt="Screen Shot 2020-09-11 at 2 39 28 PM" src="https://user-images.githubusercontent.com/71122085/92892100-0ad9ec80-f44b-11ea-8339-25c97368b8d7.png">

**Comment by justusdieckmann** [comment]
Thanks for your bug report. You shouldn't be able to use the 'Require Grade' as activity completion setting if you didn't configure the grade options. This should be fixed now on the master branch :)

Justus
