### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by paidge** [learnweb/moodle-mod_moodleoverflow#70]
Hi,
I just translated the plugin in french for my personnal Moodle instance. I read the process of submitting translations but I guess I have to type or copy/paste every Strings one per one ?! Is it possible to submit my language file by a pull request ?

**Comment by NinaHerrmann** [comment]
Hey Paidge, 
Thank you for your contribution! 
Translations can be submitted in https://lang.moodle.org/. You will need to create a moodle account and search for the plugin and then you can add your translation. That would be great! 
Thanks in advance, Nina

**Comment by paidge** [comment]
I'm afraid that the process on https://lang.moodle.org is too long for me. I have to copy/paste all the strings while my language file is ready...

**Comment by NinaHerrmann** [comment]
I am sorry to hear that you do not have the time to let the community profit from your translations. Maybe you can post the translations here so I can insert them into the moodle lang package :)

**Comment by paidge** [comment]
I took the time to translate it and to share it but I thousght I could directly submit my language file : 
`<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * English strings for moodleoverflow
 *
 * You can have a rather longer description of the file as well,
 * if you like, and it can span multiple lines.
 *
 * @package   mod_moodleoverflow
 * @copyright 2017 Kennet Winter <k_wint10@uni-muenster.de>
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

// Default strings.
$string['modulename']             = 'Moodleoverflow';
$string['modulenameplural']       = 'Moodleoverflows';
$string['modulename_help']        = 'Le module Moodleoverflow permet aux participants d\'utiliser une structure de forum sous forme de questions-réponses. L\'affichage du forum n\'est pas chronologique car le tri dépend du vote collaboratif plutôt que de l\'heure. Comme pour StackOverflow';
$string['moodleoverflowfieldset'] = 'Exemple de jeu de champs personnalisé';
$string['moodleoverflowname']     = 'Nom Moodleoverflow';
$string['moodleoverflow']         = 'Moodleoverflow';
$string['pluginadministration']   = 'Administration Moodleoverflow';
$string['pluginname']             = 'Moodleoverflow';

// Capabilities.
$string['moodleoverflow:addinstance']         = 'Ajouter une nouvelle insance Moodleoverflow';
$string['moodleoverflow:allowforcesubscribe'] = 'Autoriser les abonnements forcés';
$string['moodleoverflow:createattachment']    = 'Créer des pièces jointes';
$string['moodleoverflow:managesubscriptions'] = 'Gérer les abonnements';
$string['moodleoverflow:ratehelpful']         = 'Marquer un message comme utile';
$string['moodleoverflow:ratepost']            = 'Evaluer un message';
$string['moodleoverflow:viewanyrating']       = 'Voir les évaluations';
$string['moodleoverflow:deleteanypost']       = 'Supprimer les messages';
$string['moodleoverflow:deleteownpost']       = 'Supprimer ses propres messages';
$string['moodleoverflow:editanypost']         = 'Editer les messages';
$string['moodleoverflow:startdiscussion']     = 'Démarrer une discussion';
$string['moodleoverflow:replypost']           = 'Répondre dans les discussions';
$string['moodleoverflow:viewdiscussion']      = 'Voir les discussions';
$string['moodleoverflow:view']                = 'Voir la liste des discussions';
$string['moodleoverflow:marksolved']          = 'Marquer un message comme solution';
$string['nowallsubscribed']                   = 'Tous les forums dans {$a} sont abonnés.';
$string['nowallunsubscribed']                 = 'tous les forums dans {$a} sont désabonnés.';

// Strings for the view.php.
$string['noviewdiscussionspermission'] = 'Vous n\'avez pas la permission de voir les discussions dans ce forum.';

// Strings for the locallib.php.
$string['addanewdiscussion']    = 'Ajouter une nouvelle discussion';
$string['nodiscussions']        = 'Il n\'y a pas encore de discussion dans ce forum.';
$string['headerdiscussion']     = 'Discussion';
$string['headerstartedby']      = 'Commencée par';
$string['headerreplies']        = 'Réponses';
$string['headerlastpost']       = 'Dernier post';
$string['headerunread']         = 'Non lu';
$string['headervotes']          = 'Votes';
$string['headerstatus']         = 'Statut';
$string['markallread']          = 'Marquer tous les messages de cette discussion comme lus.';
$string['delete']               = 'Supprimer';
$string['parent']               = 'Montrer le parent';
$string['markread']             = 'Marquer comme lu';
$string['markunread']           = 'Marquer comme non lu';
$string['permalink']            = 'Lien permanent';
$string['postbyuser']           = '{$a->post} écrit par {$a->user}';
$string['bynameondate']         = 'écrit par {$a->name} ({$a->rating}) - {$a->date}';
$string['bynameondatenorating'] = 'écrit par {$a->name} - {$a->date}';
$string['deletesure']           = 'Êtes-vous sûr(e) de vouloir supprimer ce message ?';
$string['deletesureplural']     = 'Êtes-vous sûr(e) de vouloir supprimer ce message et oues ses réponses ? ({$a} posts)';

// Strings for the settings.php.
$string['configmanydiscussions']     = 'Nombre maximum de discussions affichées par page dans une instance Moodleoverflow.';
$string['manydiscussions']           = 'Discussions par page';
$string['maxattachmentsize']         = 'Taille maximale des fichiers joints';
$string['maxattachmentsize_help']    = 'Ce réglage détermine la taille max d\'un fichier pouvant êre ataché à un message.';
$string['configmaxbytes']            = 'Taille maximale par défaut pour toutes les pièces jointes des forums du site.';
$string['maxattachments']            = 'Nombre maximal de pièces jointes';
$string['maxattachments_help']       = 'Ce réglage détermine le nombre max de fichiers pouvant être ataché à un message du forum.';
$string['configmaxattachments']      = 'Nombre maximal de pièces jointes auttorisées par message.';
$string['maxeditingtime']            = 'Durée maximale pendan laquelle un message peu êre édité par son propriétaire (en sec)';
$string['configmaxeditingtime']      = 'Valeur par défaut : 3600s (1h)';
$string['configoldpostdays']         = 'Nbre de jours à partir duquel un message est considéré comme lu.';
$string['oldpostdays']               = 'Read after days';
$string['trackingoff']               = 'Off';
$string['trackingon']                = 'Forcé';
$string['trackingoptional']          = 'Optionnel';
$string['trackingtype']              = 'Read tracking';
$string['configtrackingtype']        = 'Réglage par défaut pour le suivi de lecture.';
$string['trackmoodleoverflow']       = 'Suivre les messages non lus';
$string['configtrackmoodleoverflow'] = 'Régler sur \'Oui\' si vous voulez suivre les messages lus/non lus de chaque utilisateur.';
$string['forcedreadtracking']        = 'Autoriser le suivi forcé de lecture';
$string['configforcedreadtracking']  = 'Allows Moodleoverflows to be set to forced read tracking. Will result in decreased performance for some users, particularly on courses with many moodleoverflows and posts. When off, any moodleoverflows previously set to Forced are treated as optional.';
$string['cleanreadtime']             = 'Marquer les vieux posts comme lus (heure)';
$string['configcleanreadtime']       = 'Heure de la journée à laquelle la table des messages lus sera vidée.';

$string['votescalevote']               = 'Réputation: Vote.';
$string['configvotescalevote']         = 'Réputation gagnée en votant.';
$string['votescaledownvote']           = 'Reputation: Vote négatif';
$string['configvotescaledownvote']     = 'Réputation reçue lors d\'un vote négatif sur vos messages.';
$string['votescaleupvote']             = 'Reputation: Vote positif';
$string['configvotescaleupvote']       = 'Réputation reçue lors d\'un vote positif sur vos messages.';
$string['votescalesolved']             = 'Reputation: Solution';
$string['configvotescalesolved']       = 'Réputation reçue lorsqu\'un de vos messages a été marqué comme solution.';
$string['votescalehelpful']            = 'Reputation: Utile';
$string['configvotescalehelpful']      = 'Réputation reçue lorsqu\'un de vos messages a été marqué comme utile.';
$string['reputationnotnegative']       = 'Réputation seulement positive?';
$string['configreputationnotnegative'] = 'Empecher la réputation des utilisateurs d\'être négative.';
$string['allowcoursereputation']       = 'Somme de la réputation à l\'intérieur d\'un cours.';
$string['configallowcoursereputation'] = 'Autoriser la somme des réputations de toutes les instances du cours courant?';
$string['maxmailingtime']              = 'Temps maximal de notificaion par courrier';
$string['configmaxmailingtime'] = 'Les messages plus vieux que ce nombre d\'heures ne seront pas envoyés aux utilisateurs. Cela peu aider à éviter les problèmes où le CRON n\'a pas été lancé depuis longtemps.';

// Strings for the post.php.
$string['invalidmoodleoverflowid'] = 'ID du Forum incorrect';
$string['invalidparentpostid']     = 'ID du message parent incorrect';
$string['notpartofdiscussion']     = 'Ce message ne faitt partie d\'une discussion!';
$string['noguestpost']             = 'Désolé, les invités ne sontt pas autorisés à poster des messages.';
$string['nopostmoodleoverflow']    = 'Désolé, vous n\'êtes pas autorisé(e) à poster dans ce forum.';
$string['yourreply']               = 'Votre réponse';
$string['re']                      = 'Re:';
$string['invalidpostid']           = 'ID de message invalide - {$a}';
$string['cannotfindparentpost']    = 'Impossible de trouver le parent du message {$a}';
$string['edit']                    = 'Modifier';
$string['cannotreply']             = 'Vous ne pouvez pas répondre à ce message';
$string['cannotcreatediscussion']  = 'Impossible de créer une nouvelle discussion';
$string['couldnotadd']             = 'Impossible poster votre message suite à une erreur inconnue';
$string['postaddedsuccess']        = 'Votre message a été ajoué avec succès.';
$string['postaddedtimeleft']       = 'Vous avez {$a} pour le modifier si vous voulez effecuer un changement.';
$string['cannotupdatepost']        = 'Vous ne pouvez pas mettre à jour ce message';
$string['couldnotupdate']          = 'Impossible de mettre à jour votre message suite à une erreur inconnue';
$string['editedpostupdated']       = 'Le message de {$a} a été mis à jour';
$string['postupdated']             = 'Votre message a été mis à jour';
$string['editedby']                = 'Modifié par {$a->name} - soumis le {$a->date}';
$string['cannotdeletepost']        = 'Vous ne pouvez pas supprimer ce message!';
$string['couldnotdeletereplies']   = 'Désolé, impossible de supprimer puisque des utilisateurs on déjà répondu';
$string['errorwhiledelete']        = 'Une erreur s\'est produite pendant la suppression de l\'enregistrement.';

// Strings for the classes/mod_form.php.
$string['subject']                     = 'Sujet';
$string['reply']                       = 'Commenter';
$string['replyfirst']                  = 'Répondre';
$string['message']                     = 'Message';
$string['discussionsubscription']      = 'S\'inscrire à la discussion';
$string['discussionsubscription_help'] = 'S\'inscrire à une discussion signifie que vous recevrez des notifications pour les nouveaux messages de cette discussion.';
$string['posttomoodleoverflow']        = 'Publier sur le forum';
$string['posts'] = 'Messages';
$string['erroremptysubject']           = 'Le sujet du message ne peut pas être vide.';
$string['erroremptymessage']           = 'Le message ne peut pas être vide.';
$string['yournewtopic']                = 'Votre nouveau sujet de discussion';

// Strings for the classes/ratings.php.
$string['postnotexist']             = 'Le message demandé n\'existe pas';
$string['noratemoodleoverflow']     = 'Désolé, vous n\'êtes pas autorisé(e) à voter dans ce forum.';
$string['configallowratingchange']  = 'Est-ce qu\'un utilisateur peut changer ses évaluations ?';
$string['allowratingchange']        = 'Autoriser les modifications des évaluations';
$string['configpreferteachersmark'] = 'Les réponses marquées comme solution par le propriétaire d\'un cours sont prioritaires face aux réponses marquées comme utiles par l\'initiateur de la discussion.';
$string['preferteachersmark']       = 'Préférer les marquages des propriétaires de cours ?';
$string['noratingchangeallowed']    = 'Vous n\'êtes pas autorisé(e) à modifier vos évaluations.';
$string['invalidratingid']          = 'L\'évaluation soumise n\'est ni positive ni négative.';
$string['notstartuser']             = 'Seulement l\'initiateur de la discussion peut marquer une réponse comme utile.';
$string['notteacher']               = 'Seulement les propriétaires de cours peuvent faire ça.';
$string['ratingtoold']              = 'Les évaluations ne peuvent être modifiées que pendant 30min. ';

// Strings for the discussion.php.
$string['invaliddiscussionid']         = 'L\'ID de la discussion est incorrect';
$string['notexists']                   = 'La discussion n\'existe plus';
$string['discussionname']              = 'Nom de la discussion';
$string['discussionlocked']            = 'Cette discussion a été verrouillée. Vous ne pouvez plus y répondre.';
$string['hiddenmoodleoverflowpost']    = 'Message caché';
$string['moodleoverflowsubjecthidden'] = 'Sujet (caché)';
$string['moodleoverflowauthorhidden']  = 'Auteur (caché)';
$string['moodleoverflowbodyhidden']    = 'Vous ne pouvez pas voir ce message, probablement parce que vous n\'avez pas écrit dans la discussion, le temps maximum d\'édition n\'est pas écoulé, la discussion n\'a pas démarré ou la discussion a expiré.';
$string['addanewreply']                = 'Ajouter une réponse';
$string['ratingfailed']                = 'Évaluation échouée. Essayez encore.';
$string['rateownpost']                 = 'Vous ne pouvez pas voter pour votre propre message.';
$string['marksolved']                  = 'Marquer comme solution';
$string['marknotsolved']               = 'Ne plus marquer comme solution';
$string['markhelpful']                 = 'Marquer comme utile';
$string['marknothelpful']              = 'Ne plus marquer comme utile';

// Strings for the readtracking.php.
$string['markreadfailed']                   = 'Un message de la discussion n\'a pas pu être marquée comme lu.';
$string['markdiscussionreadsuccessful']     = 'La discussion a été marquée comme lue.';
$string['markmoodleoverflowreadsuccessful'] = 'Tous les messages ont été marqués comme lus.';
$string['noguesttracking']                  = 'Désolé, les invités ne son pas auttorisés à régler les options de suivi.';

// OTHER.
$string['messageprovider:posts']        = 'Notification des nouveaux messages';
$string['unknownerror']                 = 'Erreur inconnue.';
$string['crontask']                     = 'Moodleoverflow maintenance jobs';
$string['taskcleanreadrecords']         = 'Moodleoverflow maintenance job pour nettoyer les vieux enregistrements lus';
$string['tasksendmails']                = 'Moodleoverflow maintenance job pour envoyer les mails';
$string['nopermissiontosubscribe']      = 'Vous n\'avez pas la permission de voir les abonnés';
$string['subscribeenrolledonly']        = 'Désolé, seulemen les utilisateurs inscrits à ce cours sont autorisés à s\'abonner aux noificaions de message.';
$string['everyonecannowchoose']         = 'Tout le monde peut maintenant choisir à être abonné';
$string['noonecansubscribenow']         = 'Les abonnements sont plus autorisés';
$string['invalidforcesubscribe']        = 'Mode d\'abonnement forcé non valide';
$string['nownotsubscribed']             = '{$a->name} ne sera pas notifié des nouveaux messages dans \'{$a->moodleoverflow}\'';
$string['cannotunsubscribe']            = 'Impossible de vous désabonner de ce forum';
$string['discussionnownotsubscribed']   = '{$a->name} ne sera pas notifié des nouveaux messages dans \'{$a->discussion}\' de \'{$a->moodleoverflow}\'';
$string['disallowsubscribe']            = 'Les abonnements ne sont pas autorisés';
$string['noviewdiscussionspermission']  = 'Vous n\'avez pas la permission de voir les discussions de ce forum';
$string['nowsubscribed']                = '{$a->name} sera notifié des nouveaux messages dans \'{$a->moodleoverflow}\'';
$string['discussionnowsubscribed']      = '{$a->name} sera notifié des nouveaux messages dans \'{$a->discussion}\' de \'{$a->moodleoverflow}\'';
$string['unsubscribe']                  = 'Se désabonner de ce forum';
$string['subscribe']                    = 'S\'abonner à ce forum';
$string['confirmunsubscribediscussion'] = 'Voulez-vous vraiment vous désabonner de cette discussion \'{$a->discussion}\' dans \'{$a->moodleoverflow}\'?';
$string['confirmunsubscribe']           = 'Voulez-vous vraiment vous désabonner de \'{$a}\'?';
$string['confirmsubscribediscussion']   = 'Voulez-vous vraiment vous abonner à cette discussion \'{$a->discussion}\' dans le forum \'{$a->moodleoverflow}\'?';
$string['confirmsubscribe']             = 'Voulez-vous vraiment vous abonner au forum \'{$a}\'?';
$string['postmailsubject']              = '{$a->courseshortname}: {$a->subject}';
$string['smallmessage']                 = '{$a->user} a posté un message dans {$a->moodleoverflowname}';
$string['moodleoverflows']              = 'Moodleoverflows';
$string['postmailinfolink']             = 'Il s\'agit de la copie d\'un message posté dans {$a->coursename}.

Pour répondre, cliquez sur ce lien: {$a->replylink}';
$string['unsubscribelink']              = 'Se désabonner de ce forum: {$a}';
$string['unsubscribediscussionlink']    = 'Se désabonner de cete discussion: {$a}';
$string['postincontext']                = 'Voir ce message dans le contexe';
$string['unsubscribediscussion']        = 'Se désabonner de cette discussion';
$string['nownottracking']               = '{$a->name} n\'est plus suivi \'{$a->moodleoverflow}\'.';
$string['nowtracking']                  = '{$a->name} est suivi \'{$a->moodleoverflow}\'.';
$string['cannottrack']                  = 'Impossible d\'arrêter le suivi de ce forum';
$string['notrackmoodleoverflow']        = 'Ne pas suivre les messages non lus';
$string['trackmoodleoverflow']          = 'Suivre les messages non lus';
$string['discussions']                  = 'Discussions';
$string['subscribed']                   = 'Abonné';
$string['unreadposts']                  = 'Messages non lus';
$string['unreadpostsnumber']            = '{$a} messages non lus';
$string['unreadpostsone']               = '1 message non lu';
$string['tracking']                     = 'Suivi';
$string['allsubscribe']                 = 'S\'abonner à tous les forums';
$string['allunsubscribe']               = 'Se désabonner de tous les forums';
$string['generalmoodleoverflows']       = 'Forums dans ce cours';
$string['subscribestart']               = 'Envoyez-moi des notifications pour tous les nouveaux messages de ce forum';
$string['subscribestop']                = 'Je ne souhaite pas être noifié des nouveaux messages dans ce forum';
$string['everyoneisnowsubscribed']      = 'Tout le monde est désormais abonné à ce forum';
$string['everyoneissubscribed']         = 'Tout le monde est abonné à ce forum';
$string['mailindexlink']                = 'Modifier vos préférences de forum: {$a}';
$string['gotoindex']                    = 'Gérer vos préférences';
$string['areaattachment']               = 'Pièces jointes';
$string['areapost']                     = 'Messages';


// EVENTS.
$string['eventdiscussioncreated']             = 'Discussion créée';
$string['eventdiscussiondeleted']             = 'Discussion supprimée';
$string['eventdiscussionviewed']              = 'Discussion vue';
$string['eventratingcreated']                 = 'Évaluation créée';
$string['eventratingupdated']                 = 'Évaluation mise à jour';
$string['eventratingdeleted']                 = 'Évaluation supprimée';
$string['eventpostcreated']                   = 'Post créé';
$string['eventpostupdated']                   = 'Post mis à jour';
$string['eventpostdeleted']                   = 'Post supprimé';
$string['eventdiscussionsubscriptioncreated'] = 'Abonnement à la discussion créé';
$string['eventdiscussionsubscriptiondeleted'] = 'Abonnement à la discussion supprimé';
$string['eventsubscriptioncreated']           = 'Abonnement créé';
$string['eventsubscriptiondeleted']           = 'Abonnement supprimé';
$string['eventreadtrackingdisabled']          = 'Suivi de lecture désactivé';
$string['eventreadtrackingenabled']           = 'Suivi de lecture activé';


$string['subscriptiontrackingheader']   = 'Abonnement et suivi';
$string['subscriptionmode']             = 'Mode d\'abonnement';
$string['subscriptionmode_help']        = 'Quand un participant est abonné à un forum cela signifie qu\'il va recevoir les notifications de publicaion sur le forum. Il y a 4 modes d\'abonnement:

* Abonnement facultatif - Les participants peuvent choisir de s\'abonner
* Abonnement forcé - out le monde est abonné et ne peut se désabonner
* Abonnement auto - Tou le monde est abonné initialement mais peut choisir de se désabonner n\'importe quand
* Abonnement désacivé - Les abonnements ne son pas autorisés

Note: Chaque modification du mode d\'abonnement n\'affectera que les futurs inscrits au cours mais pas les utilisateurs existants.';
$string['subscriptionoptional']         = 'Abonnement facultatif';
$string['subscriptionforced']           = 'Abonnement forcé';
$string['subscriptionauto']             = 'Abonnement auto';
$string['subscriptiondisabled']         = 'Abonnement désactivé';
$string['trackingoff']                  = 'Désactivé';
$string['trackingon']                   = 'Forcé';
$string['trackingoptional']             = 'Facultatif';
$string['trackingtype']                 = 'Suivi de lecture';
$string['trackingtype_help']            = 'Le suivi de lecture permet aux participants de facilement vérifier quels messages ils n\'on pas encore vus en surlignant les nouveaux.

Si le rélage est sur Facultatif, le suivi est activé par défaut mais les participants peuvent le désactiver.

Si \'Autoriser le suivi de lecture forcé\' est activé dans l\'administration du site, alors une autre option est disponible - forcé. Cela signifie que le suivi est toujours activé.';
$string['ratingheading']                = 'Évaluation et réputation';
$string['starterrating']                = 'Utile';
$string['teacherrating']                = 'Solution';
$string['ratingpreference']             = 'Afficher en premier';
$string['ratingpreference_help']        = 'Les réponses peuvent être marquées soit en tant que solution soit utiles. Cette option définit lequel des deux sera affiché en premier dans la discussion. Il y a 2 options:

* Utile - Un message marqué comme utile sera épinglée en haut de la discussion
* Résolu - Un message marqué comme solution par l\'enseignant sera épinglé en haut de la discussion';
$string['allownegativereputation']      = 'Autoriser la réputation négative?';
$string['allownegativereputation_help'] = 'Si oui, la réputation des utilisateurs dans un cours ou un module pourra êre négative. Si non, la réputation ne descendra pas en-dessous de zéro.';
$string['coursewidereputation']         = 'Réputation entre les modules?';
$string['coursewidereputation_help']    = 'Si oui, la réputation des utilisateurs de tous les modules moodleoverflow de ce cours sera additionnée.';
$string['clicktounsubscribe']           = 'Vous êtes abonné(e) à cette discussion. Cliquez pour vous désabonner.';
$string['clicktosubscribe']             = 'Vous n\'êtes pas abonné(e) à cette discussion. Cliquez pour vous abonner.';
$string['attachment']                   = 'Pièce jointe';
$string['attachments']                  = 'Pièces jointes';
$string['attachment_help']              = 'Vous pouvez joindre un ou plusieurs fichiers à un message du forum. Si vous attachez une image, elle sera affichée après le message.';

// Templates.
$string['helpfulanswer'] = 'Le propriétaire de la question a reconnu cette réponse comme étant utile.';
$string['solvedanswer']  = 'Ce message est marqué comme solution.';
$string['bestanswer']    = 'Le propriétaire de la question ou un propriéttaire du cours a reconnu cette réponse comme étant la meilleure.';
$string['reputation'] = 'Réputation';
$string['upvote'] = 'Vote positif';
$string['upvotenotchangeable'] = 'Vote positif (non modifiable)';
$string['noupvote'] = 'Pas de vote positif';
$string['downvote'] = 'Vote négatif';
$string['downvotenotchangeable'] = 'Vote négatif (non modifiable)';
$string['nodownvote'] = 'Pas de vote négatif';

// Privacy.
$string['privacy:metadata:core_files'] = 'Moodleoverflow stocke les fichiers uploadés par l\'utilisateur pour faire partie du message du forum.';
$string['privacy:metadata:moodleoverflow_discussions'] = 'Information sur les discussions de forum. Cela inclut quelles discussions un utilisateur a lancées.';
$string['privacy:metadata:moodleoverflow_discussions:name'] = 'Le nom de la discussion.';
$string['privacy:metadata:moodleoverflow_discussions:userid'] = 'L\'ID de l\'utilisateur qui a démarré la discussion.';
$string['privacy:metadata:moodleoverflow_discussions:timemodified'] = 'Heure à laquelle la discussion (par ex un message) a été modifiée en dernier.';
$string['privacy:metadata:moodleoverflow_discussions:usermodified'] = 'L\'ID du dernier utilisateur qui a modifié la discussion';

$string['privacy:metadata:moodleoverflow_posts'] = 'Informations sur les messages de forum. Cela inclut les données des messages postés par un utilisateur.';
$string['privacy:metadata:moodleoverflow_posts:discussion'] = 'L\'ID de la discussion dont fait partie ce message.';
$string['privacy:metadata:moodleoverflow_posts:parent'] = 'L\'ID du message auquel fait référence ce message.';
$string['privacy:metadata:moodleoverflow_posts:userid'] = 'L\'ID de l\'utilisateur qui a soumis ce message.';
$string['privacy:metadata:moodleoverflow_posts:created'] = 'Date à laquelle ce message a été créé.';
$string['privacy:metadata:moodleoverflow_posts:modified'] = 'Dernière date à laquelle ce message a été modifié.';
$string['privacy:metadata:moodleoverflow_posts:message'] = 'Texte de ce message.';

$string['privacy:metadata:moodleoverflow_read'] = 'Informations sur le suivi de lecture des messages. Cela inclut quand les messages ont été lus par un utilisateur.';
$string['privacy:metadata:moodleoverflow_read:userid'] = 'L\'ID de l\'utilisateur qui a lu ce message.';
$string['privacy:metadata:moodleoverflow_read:discussionid'] = 'L\'ID de la discussion à laquelle appartient le message lu.';
$string['privacy:metadata:moodleoverflow_read:postid'] = 'L\'ID du message qui a été lu.';
$string['privacy:metadata:moodleoverflow_read:firstread'] = 'Date à laquelle le message a été lu pour la première fois.';
$string['privacy:metadata:moodleoverflow_read:lastread'] = 'Date à laquelle le message a été lu pour la dernière fois par l\'utilisateur.';

$string['privacy:metadata:moodleoverflow_subscriptions'] = 'Informations sur les abonnements aux forums. Cela inclut les forums auxquels un uttilisateur s\'est abonné.';
$string['privacy:metadata:moodleoverflow_subscriptions:userid'] = 'L\'ID de l\'utilisateur qui s\'est abonné à un forum.';
$string['privacy:metadata:moodleoverflow_subscriptions:moodleoverflow'] = 'L\'ID du forum Moodleoverflow auquel l\'utilisateur s\'est abonné.';

$string['privacy:metadata:moodleoverflow_discuss_subs'] = 'Informations sur les abonnements aux discussions de forum individuelles. Cela inclut quand un utilisateur a choisi de s\'abonner ou de se désabonner d\'une discussion.';
$string['privacy:metadata:moodleoverflow_discuss_subs:userid'] = 'L\'ID de l\'utilisateur qui a modifié les réglages d\'abonnement.';
$string['privacy:metadata:moodleoverflow_discuss_subs:discussion'] = 'L\'ID de la discussion qui a été abonnée / désabonnée.';
$string['privacy:metadata:moodleoverflow_discuss_subs:preference'] = 'Heure de début de l\'abonnement.';

$string['privacy:metadata:moodleoverflow_ratings'] = 'Informations sur les évaluations des messages. Cela inclut quand un utilisateur a voté pour un message ainsi que son évaluation.';
$string['privacy:metadata:moodleoverflow_ratings:userid'] = 'L\'ID de l\'utilisateur qui a soumis l\'évaluation.';
$string['privacy:metadata:moodleoverflow_ratings:postid'] = 'L\'ID du message qui a été évalué.';
$string['privacy:metadata:moodleoverflow_ratings:discussionid'] = 'L\'ID de la discussion à laquelle appartient le message évalué.';
$string['privacy:metadata:moodleoverflow_ratings:moodleoverflowid'] = 'L\'ID du forum Moodleoverflow qui contient le message évalué.';
$string['privacy:metadata:moodleoverflow_ratings:rating'] = 'Évaluation soumise. 0 = neutre, 1 = négative, 2 = positive, 3 = utile, 4 = solution';
$string['privacy:metadata:moodleoverflow_ratings:firstrated'] = 'Date à laquelle l\'évaluation a été soumise.';
$string['privacy:metadata:moodleoverflow_ratings:lastchanged'] = 'Date à laquelle l\'évaluation a été modifiée pour la dernière fois.';

$string['privacy:metadata:moodleoverflow_tracking'] = 'Informations sur le suivi des forums. Cela inclut quels forums un utilisateur ne suit pas.';
$string['privacy:metadata:moodleoverflow_tracking:userid'] = 'L\'ID de l\'utilisateur qui ne suit pas le forum.';
$string['privacy:metadata:moodleoverflow_tracking:moodleoverflowid'] = 'L\'ID du forum moodleoverflow qui n\'est pas suivi par l\'utilisateur.';

$string['privacy:metadata:moodleoverflow_grades'] = 'Informations sur le rang qu\'un utilisateur a obtenue pour sa contribution à un forum.';
$string['privacy:metadata:moodleoverflow_grades:userid'] = 'L\'ID de l\'utilisateur qui a obenu le rang.';
$string['privacy:metadata:moodleoverflow_grades:moodleoverflowid'] = 'L\'ID du forum moodleoverflow dans lequel l\'utilisateur a obtenu le rang.';
$string['privacy:metadata:moodleoverflow_grades:grade'] = 'Rang que l\'utilisateur a obtenu.';

$string['privacy:anonym_discussion_name'] = 'Nom de discussion anonyme';
$string['privacy:anonym_post_message'] = 'Ce contenu a été supprimé.';
$string['privacy:anonym_user_name'] = 'Anonyme';

$string['privacy:subscribedtoforum'] = 'Vous êtes abonné(e) à ce forum.';
$string['privacy:discussionsubscriptionpreference'] = 'Vous avez choisi la préfèrence d\'abonnement à la discussion suivante pour ce forum: "{$a->preference}"';
$string['privacy:readtrackingdisabled'] = 'Vous avez choisi de ne pas suivre les messages que vous avez lus dans ce forum.';
$string['privacy:postwasread'] = 'Ce message a été lu en premier le {$a->firstread} aet plus récemment le {$a->lastread}';
$string['privacy:grade'] = 'Votre rang pour ce forum Moodleoverflow.';

$string['scalefactor'] = 'Facteur d\'échelle';
$string['scalefactor_help'] = 'L\'évaluation de l\'utilisateur est divisée par le facteur d\'échelle pour obtenir le rang de chaque utilisateur. Si le rang résultant est plus haut que le rang max, la valeur est limitée au maximum spécifié';
$string['scalefactorerror'] = 'Le facteur d\'échelle doit être un entier positif différent de zéro';
$string['grademaxgradeerror'] = 'Le rang max doit être un entier positif différent de zéro';
$string['updategrades'] = 'Mise à jour des rangs';
$string['gradesreport'] = 'Rapport de rangs';
$string['gradesupdated'] = 'Rangs mises à jour';
$string['taskupdategrades'] = 'Tâche de maintenance Moodleoverflow pour mettre à jour les rangs';`

**Comment by NinaHerrmann** [comment]
What do you mean by submitting it? In any case, thank you, it might be helpful to other users of the plugin!

**Comment by paidge** [comment]
With git for example.

**Comment by NinaHerrmann** [comment]
This is not the way how lang files are handled in Moodle.

**Comment by paidge** [comment]
I understood. But this is a very long process. Nevertheless I took time to find a solution to share that work :)

**Comment by justusdieckmann** [comment]
Hey @paidge,

actually, it seems like you can import a moodle php lang file into the moodle translator at https://lang.moodle.org/local/amos/stage.php (once logged in).
So you'll just need to create a new file called `moodleoverflow.php`, put `<?php` as the first line, followed by all the $string['...'] = '...' definitions. Then you can just import the file in the amos staging area and won't need to copy paste every string into it's own field :)

Greetings
Justus

**Comment by paidge** [comment]
Very nice ! I had not seen this functionnality. Thanks. I just submitted my language file :)
