### ISSUE TITLE
An error occurs on Moodle system when deleting a course which has a Moodleoverflow activity.

### ISSUE THREAD

**Issue by Sophia-Xiong** [learnweb/moodle-mod_moodleoverflow#72]
Steps to reproduce:
1. Create a new course which has a full name as “course 1” and a short name as “c1”;
2. Go to “course 1” web page;
3. Click “Turn editing on” button and create a Moodleoverflow activity named “moodleoverflow for course 1”;
4. Click “Turn editing off” button;
5. Navigate to “Site administration”/”Courses”/”Manage courses and categories”;
6. Find “course 1” and click the recycle bin icon on the right side of it;
7. Click “Delete” button on the pop-up confirmation dialog;
 
Expected result:
“course 1” is successfully deleted.
 
Actual result:
“course 1” is not deleted and the error saying “_Field "moodleoverflow" does not exist in table "moodleoverflow_grades"_” occurs.
Please refer to the attached screenshot.
 
<img width="2012" alt="ActualResult" src="https://user-images.githubusercontent.com/71122085/105947823-cae76f00-60a4-11eb-97e5-7c4a002f6599.png">

I found a workaround to delete “course 1”. Firstly, in the database delete the activity “moodleoverflow for course 1”. The SQL is “_delete from mdl_moodleoverflow where name='moodleoverflow for course 1';_”. Secondly, delete the course “course 1” again on the web page. You can see that “course 1” is successfully deleted this time.

**Comment by NinaHerrmann** [comment]
Hey I created a separate branch which should fix it, but I do not have the time to test it do you mind testing it? :) 
Cheers, 
Nina

**Comment by Sophia-Xiong** [comment]
Glad to see your quick response! But I'm a data analyst, I don't have a test environment. :-(

**Comment by NinaHerrmann** [comment]
Then it would be nice if you could contact the person responsible for your Moodle environment. :)

**Comment by Sophia-Xiong** [comment]
Please send the patch to me.

**Comment by NinaHerrmann** [comment]
diff --git a/lib.php b/lib.php
index 968a29c..555292c 100644
--- a/lib.php
+++ b/lib.php
@@ -269,7 +269,7 @@ function moodleoverflow_delete_instance($id) {
     // Delete the subscription elements.
     $DB->delete_records('moodleoverflow_subscriptions', array('moodleoverflow' => $moodleoverflow->id));
     $DB->delete_records('moodleoverflow_discuss_subs', array('moodleoverflow' => $moodleoverflow->id));
-    $DB->delete_records('moodleoverflow_grades', array('moodleoverflow' => $moodleoverflow->id));
+    $DB->delete_records('moodleoverflow_grades', array('moodleoverflowid' => $moodleoverflow->id));

     // Delete the discussion recursivly.
     if ($discussions = $DB->get_records('moodleoverflow_discussions', array('moodleoverflow' => $moodleoverflow->id))) {

**Comment by NinaHerrmann** [comment]
Thanks for your support!

**Comment by Sophia-Xiong** [comment]
Could you send me the ZIP file of the updated version?

**Comment by NinaHerrmann** [comment]
You can go in this repository to the tab code. Then on the left-hand side, you switch from master to the other branch. Finally, you click the green Code Button on the right-hand side and in the opening menu klick download ZIP. :)

**Comment by Sophia-Xiong** [comment]
Hi Nina,
I installed the updated plugin and followed steps described above. The bug is fixed! 👍
