### ISSUE TITLE
lib.php should not require_once() config.php

### ISSUE THREAD

**Issue by davosmith** [learnweb/moodle-mod_moodleoverflow#74]
https://github.com/learnweb/moodle-mod_moodleoverflow/blob/a297dd5ef7c1e3c3a0bf3b75fa7bc007a2a12d07/lib.php#L33

There is no valid reason to require_once() config.php at the top of this plugin's lib.php file (as it must have been included already, if the previous `defined('MOODLE_INTERNAL')||die();` line was successful).

Whilst this doesn't directly cause a problem in standard Moodle, it does cause an installation error with Totara 13 (you may well not have any plan to support Totara with your plugin, but this is a simple correction, that won't affect how the plugin works in Moodle, so I hope you'll consider it).

Thanks

**Comment by NinaHerrmann** [comment]
Fixed in #112
