### ISSUE TITLE
Should users be able to upvote their own post?

### ISSUE THREAD

**Issue by mudrd8mz** [learnweb/moodle-mod_moodleoverflow#8]
It does not feel right.

**Comment by Dagefoerde** [comment]
Well, probably they shouldn't ;)

**Comment by mudrd8mz** [comment]
But they are :-)

**Comment by Dagefoerde** [comment]
Sorry, my response should have come with a label :smile:

**Comment by mudrd8mz** [comment]
No worries, I got it.

**Comment by Dagefoerde** [comment]
Confirmed as closed by PR #6 after additional changes (b1afa8d).
