### ISSUE TITLE
Issues highlighted by admin/cli/check_database_schema.php #66 

### ISSUE THREAD

**Issue by abias** [learnweb/moodle-mod_moodleoverflow#84]
Every now and then, we are running the admin/cli/check_database_schema.php script in our Moodle installation.

This time, this issue was highlighted:

```
-------------------------------------------------------------------------------
moodleoverflow_grades
 * column 'late' is not expected (I)
 * column 'completed' is not expected (I)
-------------------------------------------------------------------------------

```

Upon investigation, I saw that there is a discrepancy between https://github.com/learnweb/moodle-mod_moodleoverflow/blob/master/db/install.xml#L161-L172 and https://github.com/learnweb/moodle-mod_moodleoverflow/blob/master/db/upgrade.php#L89-L98. The first does not define these two columns for new installations, the second (which became effective in our Moodle instance as we are using this plugin for a long time now) adds these columns for upgraded installations.

May I ask you to double-check if these two columns are used today by the plugin and align both files properly?

Thanks in advance,
Alex

**Comment by justusdieckmann** [comment]
Hi Alex,

thanks for the notice! The fields are completely unnecessary, this will be fixed in #85.

Justus
