### ISSUE TITLE
Add admin kill switch and / or capability to the new anonymous posts feature

### ISSUE THREAD

**Issue by abias** [learnweb/moodle-mod_moodleoverflow#88]
Hi all,

I would like to thank you for implementing the anonymous post feature recently!
This is highly appreciated, especially as the Moodle core feature for user disguises (https://tracker.moodle.org/browse/MDL-1071) has been pending for many years now.

However, in many organizations introducing anonymous forums will require some more organizational work than just upgrading a plugin from v3.11-r2 to v3.11-r3. Especially, it has to be communicated clearly for what this feature should be used and for what not. Additionally, some organizations might not want to use the anonymous feature at all, but will want to continue to use Moodleoverflow.

Against this background, I would like to encourage you to add an admin kill switch and / or a dedicated capability to this new feature to give the admin the control if, when and for whom he wants to enable this feature.

Thanks for your consideration.

Cheers,
Alex

**Comment by justusdieckmann** [comment]
Hey Alex,

sorry for the late reply. It seems I already begun this in #92 (which was released in v4.0-r1), but then ... forgot to actually make the admin setting affect anything? :neutral_face: 
This will be fixed with #97.

Greetings,
Justus :)
