### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by pejhab** [learnweb/moodle-mod_moodleoverflow#91]
Hello,

This is a great plugin indeed and I have been using it extensively in the last few months. 

However, there are certain limitations compared with the standard forum:

1. The forum posts and discussions do not appear on the student profile page, which makes it quite difficult to follow things up when students are engaged in several Overflow Forums in different courses.

2. Missing features especially the ability to "Lock discussions" if too many posts are made by the same person in a given period of time, which to me is essential for a well-regulated discussion forum. Word count wouldn't be bad either. 

Thanks again for your plugin!

**Comment by pejhab** [comment]
3. Am I missing something or there is no way to "search" in the forum?

**Comment by pejhab** [comment]
I see there have been no replies from the developers on this forum for over a year. We all appreciate the good work you are doing and understand that you probably have your hands full with more urgent things. But could you let us know if our posts and comments are bring considered and what the roadmap is. I'm asking this because I really wish I could use Overflow more extensively with my students if it weren't for certain limitations. Hence my question about the roadmap. Thanks again for your wonderful plugin!

**Comment by NinaHerrmann** [comment]
Hey @pejhab,
to be fair we have done stuff in the last year. But if we do not have the resources to implement a feature request immediatly we will not comment on issues, leaving them open to the community. If we planning to do it we will comment on it. Roadmaps are hard to determine as, in the past years, we were regularly distracted by building exam systems, having work place cancellations and many more. To be honest, I would prefer building new features, but as we are highly limited in our resources I do not want to make promises about new releases. 
Thanks for your understanding!

**Comment by pejhab** [comment]
I perfectly understand.

To elaborate further, I think the following enhancements would really be welcome and very useful. 

1.  The ability to reply inline to a forum post/discussion. This has been around since Moodle 3.7 I think.

2. The ability to limit the number of posts per time period for each user, e.g. 3 per day or 10 per week, which to me is essential for a well-regulated forum. 

3. The forum posts and discussions should appear on the student profile page. Otherwise it'll be quite difficult to follow things up when students are engaged in several Overflow Forums in different courses.

4. Word count would be a useful addition. The ability to limit the number of words in a post, e.g. only 100-150 characters etc, would be extremely useful. 

PS Would it be better if I posted each of the above items separately?

**Comment by NinaHerrmann** [comment]
@pejhab  Sorry for not keeping up! 

Yes posting the features separately would help us! 

- 2 & 4 sound easily feasible 
- I know 1 is really important to a lot of users, however I fear it is not easy to "copy and paste" from other functionality - it is not the next feature we will tackle. - Help wanted
-  3 I agree, but we have to do some research if we can easily inject code in core pages...
